DELIMITER //
DROP PROCEDURE WhatNextOverlord //
CREATE PROCEDURE WhatNextOverlord(
  IN DDI VARCHAR(32),
  IN UNIQUEID VARCHAR(32),
  IN CALLERID VARCHAR(32),
  IN FULLIVRINPUT VARCHAR(32),
  IN ENTRYPOINT VARCHAR(32),
  IN COMMANDSTATUS VARCHAR(32)
)
BEGIN
  SELECT * FROM TheOverlord ORDER BY RAND() LIMIT 1;
END //
DELIMITER ;
